name: Libogc-fast-sdl2
on:
  push:
    branches:
    - sdl2
jobs:
  build-wii:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile
      run: |
        make -f Makefile.wiifast
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: gnuboy-wii
        path: |
          ./*.dol
